name: HelloWorld

author: Shawn Garner
website: https://www.shawngarner.dev
main: dev.shawngarner.minecraft.plugins.hello.HelloWorld

commands:
  hello:
    description: Say Hello to everyone!
    usage: /hello [optional message]

version: 0.1
